import { addDays, setHours, setMinutes, startOfDay } from "date-fns";

import type { Reservation } from "@/entities/reservation/model/types";

function createDate(
  referenceDate: Date,
  dayOffset: number,
  hour: number,
  minute = 0,
) {
  const day = addDays(startOfDay(referenceDate), dayOffset);
  return setMinutes(setHours(day, hour), minute).toISOString();
}

function createCreatedAt(referenceDate: Date, daysAgo: number) {
  return addDays(referenceDate, -daysAgo).toISOString();
}

export function createReservationsSeed(
  referenceDate = new Date(),
): Reservation[] {
  return [
    {
      id: "reservation-1",
      tableId: "table-12",
      guestName: "Мадина Ержанова",
      guestPhone: "+77051112233",
      guestsCount: 8,
      reservationDate: createDate(referenceDate, 0, 18),
      durationMinutes: 240,
      comment: "День рождения, нужен торт",
      status: "CONFIRMED",
      createdAt: createCreatedAt(referenceDate, 5),
    },
    {
      id: "reservation-2",
      tableId: "table-4",
      guestName: "Айгерим Сатпаева",
      guestPhone: "+77011234567",
      guestsCount: 3,
      reservationDate: createDate(referenceDate, 0, 19),
      durationMinutes: 120,
      comment: "У окна, пожалуйста",
      status: "CONFIRMED",
      createdAt: createCreatedAt(referenceDate, 3),
    },
    {
      id: "reservation-3",
      tableId: "table-9",
      guestName: "Данияр Ахметов",
      guestPhone: "+77029876543",
      guestsCount: 4,
      reservationDate: createDate(referenceDate, 0, 20, 30),
      durationMinutes: 90,
      status: "PENDING",
      createdAt: createCreatedAt(referenceDate, 1),
    },
    {
      id: "reservation-4",
      tableId: "table-21",
      guestName: "Арман Бекжанов",
      guestPhone: "+77074445566",
      guestsCount: 6,
      reservationDate: createDate(referenceDate, 0, 21),
      durationMinutes: 180,
      comment: "VIP, просили кальян",
      status: "CONFIRMED",
      createdAt: createCreatedAt(referenceDate, 4),
    },
    {
      id: "reservation-5",
      tableId: "table-7",
      guestName: "Алина Нургалиева",
      guestPhone: "+77773334455",
      guestsCount: 2,
      reservationDate: createDate(referenceDate, -1, 17),
      durationMinutes: 120,
      status: "COMPLETED",
      createdAt: createCreatedAt(referenceDate, 7),
    },
    {
      id: "reservation-6",
      tableId: "table-14",
      guestName: "Руслан Ибраев",
      guestPhone: "+77085556677",
      guestsCount: 2,
      reservationDate: createDate(referenceDate, 1, 15),
      durationMinutes: 120,
      status: "CANCELLED",
      createdAt: createCreatedAt(referenceDate, 2),
    },
    {
      id: "reservation-7",
      tableId: "table-2",
      guestName: "София Ким",
      guestPhone: "+77015550102",
      guestsCount: 4,
      reservationDate: createDate(referenceDate, 0, 17, 30),
      durationMinutes: 120,
      comment: "Стол подальше от прохода",
      status: "CONFIRMED",
      createdAt: createCreatedAt(referenceDate, 4),
    },
    {
      id: "reservation-8",
      tableId: "table-6",
      guestName: "Тимур Омаров",
      guestPhone: "+77025550108",
      guestsCount: 7,
      reservationDate: createDate(referenceDate, 0, 20),
      durationMinutes: 180,
      comment: "Семейный ужин",
      status: "CONFIRMED",
      createdAt: createCreatedAt(referenceDate, 6),
    },
    {
      id: "reservation-9",
      tableId: "table-16",
      guestName: "Жанна Алимова",
      guestPhone: "+77035550116",
      guestsCount: 5,
      reservationDate: createDate(referenceDate, 0, 18, 30),
      durationMinutes: 120,
      comment: "Приватный зал",
      status: "CONFIRMED",
      createdAt: createCreatedAt(referenceDate, 2),
    },
    {
      id: "reservation-10",
      tableId: "table-20",
      guestName: "Мирас Сейдахмет",
      guestPhone: "+77045550120",
      guestsCount: 6,
      reservationDate: createDate(referenceDate, 0, 17),
      durationMinutes: 150,
      comment: "На террасе, если не будет дождя",
      status: "CONFIRMED",
      createdAt: createCreatedAt(referenceDate, 3),
    },
    {
      id: "reservation-11",
      tableId: "table-22",
      guestName: "Аружан Нурова",
      guestPhone: "+77055550122",
      guestsCount: 3,
      reservationDate: createDate(referenceDate, 0, 19, 30),
      durationMinutes: 90,
      status: "PENDING",
      createdAt: createCreatedAt(referenceDate, 1),
    },
    {
      id: "reservation-12",
      tableId: "table-23",
      guestName: "Ерлан Муратов",
      guestPhone: "+77065550123",
      guestsCount: 6,
      reservationDate: createDate(referenceDate, 0, 21),
      durationMinutes: 120,
      comment: "Годовщина",
      status: "CONFIRMED",
      createdAt: createCreatedAt(referenceDate, 5),
    },
    {
      id: "reservation-13",
      tableId: "table-3",
      guestName: "Камила Абдрахманова",
      guestPhone: "+77075550103",
      guestsCount: 5,
      reservationDate: createDate(referenceDate, 0, 16),
      durationMinutes: 120,
      status: "CANCELLED",
      createdAt: createCreatedAt(referenceDate, 3),
    },
    {
      id: "reservation-14",
      tableId: "table-15",
      guestName: "Никита Волков",
      guestPhone: "+77085550115",
      guestsCount: 4,
      reservationDate: createDate(referenceDate, -1, 20),
      durationMinutes: 120,
      status: "COMPLETED",
      createdAt: createCreatedAt(referenceDate, 8),
    },
    {
      id: "reservation-15",
      tableId: "table-1",
      guestName: "Диана Садыкова",
      guestPhone: "+77095550101",
      guestsCount: 2,
      reservationDate: createDate(referenceDate, 1, 18),
      durationMinutes: 90,
      comment: "Нужен детский стул",
      status: "CONFIRMED",
      createdAt: createCreatedAt(referenceDate, 2),
    },
  ];
}
